image:
    file: .gitpod.dockerfile
ports:
- port: 8888
  onOpen: open-browser
- port: 8889
  onOpen: open-browser
- port: 5000
  onOpen: notify
tasks:
- command: conda init
- command: conda activate base
- command: echo "Execute: $jupynb"
- init: echo -e "\nalias jupynb="\""jupyter notebook --ServerApp.allow_origin=\\'\$(gp url 8888)\\' --ServerApp.ip='*' --ServerApp.token='' --ServerApp.password=''"\" >> ~/temp
- init: echo -e "\nalias jupylab="\""jupyter lab --ServerApp.allow_origin=\\'\$(gp url 8888)\\' --ServerApp.ip='*' --ServerApp.token='' --ServerApp.password=''"\" >> ~/temp
- init: . /home/gitpod/anaconda3/etc/profile.d/conda.sh && conda activate base && pip install -r requirements.txt